config/routes.rb
#encoding:utf-8
ControleFichaFuncional::Application.routes.draw do
  scope '(:locale)' do
    resources :control, :only =>[:index, :get_order_carga],:collection=> { :receive_all => :put } 
    
    resources :usuarios, :only =>[:index, :edit, :update_password]
    
    resources :fichas, :only => [:index, :new, :edit, :create, :update, :destroy]
    
    resources :pensionistas
  
    resources :ex_servidores
    
    resources :line_items
    
    resources :special_line_items
    
    resources :carts
    
    resources :special_carts
    
    resources :order_cargas,:only => [:index, :new, :edit, :create, :destroy]

    resources :special_order_cargas,:only => [:new, :create, :destroy]
    
    resources :search, :only =>[:track, :track_by_sector, :locate_string, :locate_fichas_by_sector]
    
    resources :setores
    # resources :ficha_steps


    devise_for :usuarios
    
    scope "/usuario" do
      get  "/minhas-configurações/edit" => "usuarios#edit", as: :keystroke
      put "/minhas-configurações/update" => "usuarios#update_password", as: :keystroke_update_password
    end

    authenticated :usuario do
      root to: "welcome#sisconff_screen"
    end

    as :order_cargas do
      get "order_cargas/:id" => "order_cargas#show",   as: :order_cargas_id
      get "etiqueta"=> "order_cargas#index", :as=>:view_cargas
      get "/espelho/:id" => "pdf_reports#imprimir_carga", :format => "pdf", :as=> :mirror
    end

    scope '/ex-servidores' do
      as :special_order_cargas do
        get "special_order_cargas/new"=> "special_order_cargas#new",   as: :new_exservidor_cargas
        
        get "special_order_cargas/:id" => "special_order_cargas#show",   as: :exservidor_cargas_id
        # get "exservidor-etiqueta"=> "special_order_cargas#index", :as=>:view_cargas
        get "/exservidor-espelho/:id" => "pdf_reports#imprimir_exservidor_carga", :format => "pdf", :as=> :exservidor_mirror
      
        post "/special_order_cargas/create" => "special_order_cargas#create", as: :special_order_carga_create
        get '/special_order_cargas/ex_servidores/:id', to: 'special_order_cargas#show', as: :special_show_carga
      end
    end

    scope "control" do
      get "/gerenciar/cargas", to: 'control#index', as: :control_set_new_carga
      get "/gerenciar/cargas/ex_servidores", to: 'control#new_ex_serv_frm', as: :control_new_ex_serv_cargas
    end

    scope "visualizar" do
      get '/cargas-pendentes', to: 'control#get_order_carga', as: :control_get_order_carga
      put '/receber-cargas-pendentes', to: 'control#receive_all', as: :control_receive_all
      get '/carga/visualizar-matriculas/:carga_id', to: 'control#view_matriculas', as: :control_view_matriculas
      get '/carga/visualizar-exservidor-matriculas/:special_carga_id', to: 'control#view_exservidor_matriculas', as: :control_view_exservidor_matriculas
    end

    as :search do
      get "search/localizar_ficha_por_matricula/",            to: 'search#track',as: :find_matricula
      get "search/localizar_servidor_por_nome/",            to: 'search#track_by_name',as: :find_server_name
      get "search/ficha/:ficha_id",         to: 'search#locate_ficha',as: :find_ficha_omega
      get "search/exservidor/:exservidor_id",      to: 'search#locate_exservidor',as: :find_exservidor_omega
      get "search/setor/ficha/:ficha_id/exservidor/:exservidor_id",  to: 'search#locate_both',as: :find_paradise_city

      get "search/",  to: 'search#locate_both',as: :find_nome

      get "search/localizar_setores/",            to: 'search#track_by_sector',as: :find_setores  
      get "search/setor/:id",               to: 'search#locate_fichas_by_sector',as: :sectors_located
      
      get "search/localizar_ficha",      to: 'search#localizar', as: :search_string
      get "search/localizar_servidor",      to: 'search#localizar_por_nome', as: :search_server
    end

    as :fichas do
      get "fichas/index"    => "fichas#index",  as: :_fichas
      get "fichas/view/:id" => "fichas#show",   as: :_show_ficha
      get "fichas/new"      => "fichas#new",    as: :_new_ficha
      get "fichas/edit/:id" => "fichas#edit",   as: :_edit_ficha
      get "fichas/create"   => "fichas#create", as: :_create_ficha
      get "fichas/update"   => "fichas#update", as: :_update_ficha
    end

    scope :sisconff do
      get '/sistema-de-controle-de-ficha-funcional', to: "welcome#sisconff_screen", as: :sisconff
      mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
    end

    scope "/welcome" do
      get "/help", to: 'welcome#help', as: :help
    end
    
    root to: "welcome#index", as: 'welcome', via: :all
  end  
end

app/controllers/search_controller.rb
#-*- coding:utf-8 -*-
class SearchController < ApplicationController
    before_action :authenticate_usuario!
    before_action :current_usuario

    respond_to :html, :xml

    def index
      session[params[:controller]]= request.fullpath
    end

    '''
      OS METODOS ABAIXO track e locate_matricula
      SÃO RESPONSAVEIS PELO MODULO DE PESQUISAR
      LOCALIZAÇÃO DA FICHA FUNCIONAL.
    '''

    def track
      @title = "Localizar"
      respond_with :html
    end

    def track_by_name
      @title = "Localizar"
      respond_with :html
    end

    def localizar
      @ficha = Ficha.find_by(matricula: remove_zero_on_the_left(params[:search_string]))
      @exservidor = ExServidor.find_by(nova_matricula: remove_zero_on_the_left(params[:search_string]))
      
      if @ficha.nil? and @exservidor.nil?
          flash[:info] = t('search.not_found')
           redirect_to find_matricula_path          
      elsif @ficha and @exservidor
         redirect_to find_paradise_city_path(@ficha.id, @exservidor.id) 
      elsif @ficha
         redirect_to(find_ficha_omega_path(@ficha.id))
      else
         redirect_to find_exservidor_omega_path(@exservidor.id)
      end
    end

    # => START::VIEWS::LOCALIZADORAS_DE_FICHAS
      def locate_ficha
        @ficha = Ficha.find_by(id: params[:ficha_id])
        @setor, @hora_da_criacao, @hora_de_recebimento = [],[],[]
        @fichas = @ficha.order_cargas.paginate(:per_page => 5, :page => params[:page])
        @pensionista = Pensionista.where(matricula: @ficha.matricula)
        session['search'] ||= request.referer
      end

      def locate_exservidor
        @exservidor = ExServidor.find(params[:exservidor_id])
        @setor, @hora_da_criacao, @hora_de_recebimento = [],[],[]
        @exservidores = @exservidor.order_cargas.paginate(:per_page => 5, :page => params[:page])
        session['search'] ||= request.referer
      end

      def locate_both
          @ficha = Ficha.find(params[:ficha_id])
          @exservidor = ExServidor.find(params[:exservidor_id])
          session['search'] ||= request.referer
      end
    # => END::VIEWS::LOCALIZADORAS_DE_FICHAS


    # => O METODO A SEGUIR É O MESMO DO DE CIMA SÓ QUE BUSCA POR NOME
      def localizar_por_nome
        @fichas= Ficha.where('match (nome) against (?)', params[:search_name]).paginate(:per_page => 10, :page => params[:page])
        @exservidores = ExServidor.where('match (nome) against (?)', params[:search_name]).paginate(:per_page => 10, :page => params[:page])
        flash[:info]= t('search.server_name_founded') if @fichas.present? and @exservidores.present?
        session['search'] ||= request.referer
      end
    # => 

    def track_by_sector
      @setores = Setor.all
      respond_with :html
    end

    def locate_fichas_by_sector
      @setor = Setor.find(params[:id])
      @fichas = @setor.fichas.paginate(:per_page => 10, :page => params[:page])
      @ex_servidores = @setor.ex_servidores.paginate(:per_page => 10, :page => params[:page])
      session['search'] ||= request.referer
    end
end
        

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_find.html.erb
<div class="header_scope">
  <%= link_to "Página Inicial >> ", sisconff_path, id: "inicial_page" %>
  <%= link_to "Localizar Ficha >> Por Matrícula", find_matricula_path, id: "current_page" %>
</div>

<br />
<h3>Informe a matricula</h3>
<%= form_tag(search_string_path, method: "GET") do %>
	<%= text_field_tag :search_string %>
	<div id="side_action_button_fichas_registration">
		<%=h submit_tag "Enviar" , :class=>"btn btn-danger btn-lg but-shadow btn-size", :id=>"button_font"%>
	</div>
	<div id="side_action_button_fichas_registration">
		<%=h link_to "Voltar", :back, :class=>"btn btn-primary btn-lg but-shadow btn-size", :id=>"button_font" %>
	</div>
<% end %>

app/views/search/_layout_preview_by_setor.html.erb
<DIV class="LadoDoMenu">
  <table class="pretty">
    <tr>
      <th><%=h "Matricula" %></th>
      <th><%=h "Nome" %></th>
      <th><%=h "Função" %></th>
      <th><%=h "Vinculo" %></th>
      
      <th><%=h "Opção" %></th>
    </tr>
    <%= yield %>
  </table>
</DIV>

app/views/search/_layout_special_preview_by_setor.html.erb
<DIV class="LadoDoMenu">
  <table class="pretty">
    <tr>
      <th><strong><%=h "Matrícula de Ex-Servidor" %></strong></th>
      <th><strong><%=h "Matrícula Funcional Antiga" %></strong></th>
      <th><strong><%=h "Nome do Servidor" %></strong></th>
      <th><strong><%=h "CPF" %></strong></th>
      <th><strong><%=h "Função" %></strong></th>
      <th><strong><%=h "Vínculo" %></strong></th>
      <th><%=h "Opção" %></th>
    </tr>
    <%=h yield %>
  </table>
</DIV>

app/views/search/localizar.html.erb
<DIV class="LadoDoMenu">
  <!-- <div id="columns"> -->
    <%= render 'find' %>
    <table class="pretty">
      <tr>
        <th><%= "Orgao Atual" %></th>
        <th><%= "Setor Atual" %></th>
      </tr>
      
        <tr>
          <td><%= "SMAGP" %></td>
            <% @fichas.each do |var| %>
              <% @setor.push(var.setor_destino.nome)  %>
            <% end %>
            <td><%= @setor.last %></td>
        </tr>
    </table>

    <BR>
    <h3>Ultimas movimentações</h3><HR />  
    <fieldset>
      <table class="pretty">
        <tr>
          <th><%=h "Matrícula" %></th>
          <th><%=h "Origem" %></th>
          <th><%=h "Destino" %></th>
          <th><%=h "Gerada por" %></th>
          <th><%=h "Data da Geração" %></th>
          <th><%=h "Recebida por" %></th>
          <th><%=h "Data do Recebimento" %></th>
          <th><%=h "Status" %></th>
        </tr>
        <% @fichas.each do |carga| %>
          <tr>
              <td><%=h @ficha.matricula %></td>
              <td><%=h carga.setor_origem.nome %></td>
              <td><%=h carga.setor_destino.nome %></td>
              <td><%=h carga.user_1.nome %></td>
              <td>
                <center><%=h formata_data(carga.created_at) %></center>
              </td>
              
                <% unless carga.user_2 %>
                  <td></td>
                  <td></td>
                <% else %>
                  <td><center><%=h carga.user_2.nome %></center></td>
                  <td><center><%=h formata_data(carga.updated_at) %></center></td>
                <% end %>
              <td><%= recebida_yes_or_no?(carga.status) %></td>
          </tr>
        <% end %>
      </table>

    <div class="flickr_pagination">
      <%= will_paginate @fichas, :previous_label => "Anterior", :next_label => "Próxima", :container => false%>
    </div>
    </fieldset>

      <BR />
      <h3><%=h  t('labels.servant_data') %></h3><HR />
      <fieldset>

      <table class="pretty">
        <tr>
          <th><%=h "Matrícula" %></th>
          <td><%=h @ficha.matricula %></td>
        </tr>
        
        <tr>
          <th><%=h "Nome" %></th>
          <td><%=h @ficha.nome %></td>
        </tr>

        <tr>
          <th><%=h "Função" %></th>
          <td><%=h @ficha.nome_funcao %></td>
        </tr>

        <tr>
          <th><%=h "Lotação" %></th>
          <td><%=h @ficha.nome_lotacao %></td>
        </tr>

        <tr>
          <th><%=h "Local de Trabalho" %></th>
          <td><%=h @ficha.nome_local_trabalho %></td>
        </tr>

        <tr>
          <th><%=h "Vinculo" %></th>
          <td><%=h @ficha.nome_vinculo %></td>
        </tr>
        
        <tr>
          <th><%=h "Situação" %></th>
          <td><%=h @ficha.situacao %></td>
        </tr>
        <tr>
          <th><%=h "Data admissão" %></th>
          <td>
            <% if @ficha.data_admissao == nil %>
            <%= label_tag "--" %>
            <% else %>
              <%=h formata_data_admissao(@ficha.data_admissao) %>
            <% end %>
          </td>
        </tr>
      </table>
    </fieldset>

    <BR />

    <h3>Dependentes</h3><HR />
    <fieldset>
          <% if @pensionista == nil %>
            <div class="NotFound" id="NenhumaMovimentacao">
              <%= image_tag("NotOk.png") + " Não há dependentes para a matrícula: #{@ficha.matricula}", id: "NotFound" %>
            </DIV>
          <% else %>  
            <table class="pretty">
              <tr>
                <th><%=h "Matrícula" %></th>
                <th><%=h "Nome"%></th>
              </tr>

              <% @pensionista.each do |w| %>  
                <TR>
                  <td><%=h w.matricula %></td>
                  <td><%=h w.nome %></td>
                </TR>
              <% end %>
            </table>
          <% end %>
    </fieldset>
  <!-- </div> -->
</div>

app/views/search/localizar_por_nome.html.erb
<%= render partial: 'find_by_name' %>

<div id="recuo">
<h3>Fichas Encontradas</h3><HR />
<fieldset>
<!-- <fieldset> -->
  <BR /><BR />
  <% if @fichas.empty? %>
    <div class="marked" id="NenhumaMovimentacao">
      <%= image_tag("NotOk.png") + "  Nome não foi localizado." %>
    </div>
  <% else %>
<table class="pretty">
  <tr>
    <th>Ficha Localizada na SMAGP</th>
    <th>Matrícula</th>
    <th>Nome</th>
    <th>Função</th>
    <th>Opção</th>
  </tr>

  <% @fichas.each do |servidor| %>
    <tr>
      <td><%=h image_tag("ok.png")%></td>
      <td id="mesma_matricula"><%=h servidor.matricula %></td>
      <td><%=h servidor.nome %></td>
      <td><%=h servidor.nome_funcao %></td>
      <td><%=h link_to "Visualizar Detalhadamente", find_ficha_omega_path(servidor.id) %></td>
    </tr>
  <% end %>
</table>
<div class="flickr_pagination pagination-mini">
  <%= will_paginate @fichas, previous_label: "Anterior", next_label: "Próxima", container: false%>
</div>
<% end %>
<!-- </fieldset> -->
<BR />
<br />
<!-- <fieldset> -->
  <BR /><BR />
  <% if @exservidores.empty? %>
    <div class="marked" id="NenhumaMovimentacao">
      <%= image_tag("NotOk.png") + "  Nome não foi localizado na base de Ex-Servidores." %>
    </div>
	<% else %>
<table class="pretty">
  <tr>
    <th>Ficha Localizada na Casa do Arquivo</th>
    <th>Matrícula de Ex-Servidor</th>
    <th>Matrícula Funcional Antiga</th>
    <th>Nome</th>
    <th>Opção</th>
  </tr>

  <% @exservidores.each do |exservidor| %>
    <tr>
      <td><%=h image_tag("ok.png")%></td>
      <td id="mesma_matricula"><%=h exservidor.nova_matricula %></td>
      <td><%=h exservidor.matricula_antiga %></td>
      <td><%=h exservidor.nome %></td>
      <td><%=h link_to "Visualizar Detalhadamente", find_exservidor_omega_path(exservidor.id) %></td>
    </tr>
  <% end %>
</table>
<div class="flickr_pagination pagination-mini">
  <%= will_paginate @exservidores, previous_label: "Anterior", next_label: "Próxima", container: false%>
</div>
<% end %>
<!-- </fieldset> -->
<BR />
<BR />
  <div id="side_action_button_fichas_registration">
    <%=h link_to "Voltar", find_matricula_path, :class=>"btn btn-primary btn-lg but-shadow btn-size", :id=>"button_font" %>
  </div>
</fieldset>
</div>

app/views/search/locate_both.html.erb
<%= render 'find' %>
<BR />
<h3>Fichas Encontradas</h3><HR />

<fieldset>
<fieldset>
	<BR /><BR />
<table class="pretty">
	<tr>
		<th>Ficha Localizada na SMAGP</th>
		<th>Matrícula</th>
		<th>Nome</th>
		<th>Opção</th>
	</tr>

	<tr>
		<td><%=h image_tag("ok.png")%></td>
		<td id="mesma_matricula"><%=h @ficha.matricula %></td>
		<td><%=h @ficha.nome %></td>
		<td><%=h link_to "Visualizar Detalhadamente", find_ficha_omega_path(@ficha.id) %></td>
	</tr>
</table>
</fieldset>
<BR />
<br />
<fieldset>
	<BR /><BR />
<table class="pretty">
	<tr>
		<th>Ficha Localizada na Casa do Arquivo</th>
		<th>Matrícula de Ex-Servidor</th>
		<th>Matrícula Funcional Antiga</th>
		<th>Nome</th>
		<th>Opção</th>
	</tr>

	<tr>
		<td><%=h image_tag("ok.png")%></td>
		<td id="mesma_matricula"><%=h @exservidor.nova_matricula %></td>
		<td><%=h @exservidor.matricula_antiga %></td>
		<td><%=h @exservidor.nome %></td>
		<td><%=h link_to "Visualizar Detalhadamente", find_exservidor_omega_path(@exservidor.id) %></td>
	</tr>
</table>
</fieldset>
<BR />
<BR />
	<div id="side_action_button_fichas_registration">
		<%=h link_to "Página Inicial", sisconff_path, :class=>"btn btn-success btn-exlg but-shadow", :id=>"button_font" %>
	</div>
</fieldset>

app/views/search/locate_exservidor.html.erb
<%=h render 'find' %>

<% if @exservidores.empty? %>
  
<% else %>
  <table class="pretty">
  <tr>
    <th><%= "Orgao Atual" %></th>
    <th><%= "Setor Atual" %></th>
  </tr>
  
    <tr>
      <td><%=h "SMAGP" %></td>
      <td><%= @exservidores.setor_atual.nome %></td>
    </tr>
</table>
<% end %>

<BR>
<h3>Ultimas movimentações</h3><HR />
<fieldset>
  <% if @exservidores.empty? %>
    <div class="NotFound" id="NenhumaMovimentacao"><%= image_tag("NotOk.png") + "  Não há movimentações para a matricula: #{@exservidor.nova_matricula}"%></div>
  <% else %>
    <table class="pretty">
      <tr>
        <th><strong><%=h "Matrícula de Ex-Servidor" %></strong></th>
        <th><strong><%=h "Matricula Funcional Antiga" %></strong></th>
        <th><%=h "Origem" %></th>
        <th><%=h "Destino" %></th>
        <th><%=h "Gerada por" %></th>
        <th><%=h "Data da Geração" %></th>
        <th><%=h "Recebida por" %></th>
        <th><%=h "Data do Recebimento" %></th>
        <th><%=h "Status" %></th>
      </tr>
      <% @exservidores.each do |carga| %>
        <tr>
            <td><%=h @exservidor.nova_matricula %></td>
            <td><%=h @exservidor.matricula_antiga %></td>
            <td><%=h carga.setor_origem.nome %></td>
            <td><%=h carga.setor_destino.nome %></td>
            <td><%=h carga.user_1.nome %></td>
            <td>
              <center><%=h formata_data(carga.created_at) %></center>
            </td>
            
              <% unless carga.user_2 %>
                <td></td>
                <td></td>
              <% else %>
                <td><center><%=h carga.user_2.nome %></center></td>
                <td><center><%=h formata_data(carga.updated_at) %></center></td>
              <% end %>
            <td><%=h recebida_yes_or_no?(carga.status) %></td>
        </tr>
      <% end %>
    </table>
    <div class="flickr_pagination pagination-mini">
      <div class="page_info">
          <%=h will_paginate @exservidores, :previous_label => "&laquo; Anterior", :next_label => "Próxima &raquo;", :container => false%>
      </div>
    </div>
  <% end %>
</fieldset>
<BR />
<h3><%=h  t('labels.ex_servant_data') %></h3><HR />
<fieldset>

<table class="pretty">
  <tr>
    <th><%=h "Matrícula de Ex-Servidor" %></th>
    <td><%=h @exservidor.nova_matricula %></td>
  </tr>

  <tr>
    <th><%=h "Matrícula Funcional Antiga" %></th>
    <td><%=h @exservidor.matricula_antiga %></td>
  </tr>
  
  <tr>
    <th><%=h "Nome" %></th>
    <td><%=h @exservidor.nome %></td>
  </tr>

  <tr>
    <th><%=h "Função" %></th>
    <td><%=h @exservidor.nome_funcao %></td>
  </tr>

  <tr>
    <th><%=h "CPF" %></th>
    <td><%=h @exservidor.cpf %></td>
  </tr>

  <tr>
    <th><%=h "Vinculo" %></th>
    <td><%=h @exservidor.vinculo %></td>
  </tr>
  
  <tr>
    <th><%=h "Data de Desligamento" %></th>
    <td>
      <% if @exservidor.data_de_desligamento == nil %>
        <%=h label_tag "--" %>
      <% else %>  
        <%=h match_string_to_date_format(@exservidor.data_de_desligamento) %>
      <% end %>
    </td>
  </tr>
 
</table>
</fieldset>

app/views/search/locate_exservidor.js.erb
$("#exservidores").html("<%= escape_javascript(redirect_to action: :locate_exservidor) %>");

app/views/search/locate_fichas_by_sector.html.erb
<div class="header_scope">
	<%=h link_to "Página Inicial ", sisconff_path, id: "inicial_page" %>
	<%=h link_to ">> Localizar Ficha >> Por Setor", find_setores_path, id: "middle_page" %>
	<%=h link_to " >> #{@setor.nome}", id: "current_page" %>
</div>
<h3>Fichas encontradas no Setor: <%= @setor.nome %></h3><HR />

<BR />
<BR />
	<h3>Fichas Funcionais Comuns</h3><HR />
	<fieldset>
		<% if @fichas.present? %>
			<%= render layout: 'layout_preview_by_setor' do |f|%>
				<% @fichas.each do |e| %>
					<tr>
						<td><%=h e.matricula %></td>
						<td><%=h e.nome %></td>
						<td><%=h e.nome_funcao %></td>
						<td><%=h e.nome_vinculo %></td>
						<td><%=h link_to "Visualizar Detalhadamente.", find_ficha_omega_path(e.id) %></td>
					</tr>
				<% end %>
			<% end %>
		<% else %>
			<div class="NotFound" id="NenhumaMovimentacao"><%=h image_tag("NotOk.png")+"  Nenhuma movimentação para Ficha Funcional Comum encontrada no Setor: #{@setor.nome}" %></div>
		<% end %>
		<div class="flickr_pagination pagination-mini">
	      <div class="page_info">
	          <%=h will_paginate @fichas, :previous_label => "Anterior", :next_label => "Próxima", :container => false%>
	      </div>
	    </div>
	</fieldset>
<BR />
<BR />
<BR />
	<h3>Fichas de Ex-Servidor</h3><HR />
	<fieldset>
		<% if @ex_servidores.present? %>
			<%= render layout: 'layout_special_preview_by_setor' do |f|%>
				<% @ex_servidores.each do |e| %>
					<tr>
						<td><%=h e.nova_matricula %></td>
						<td><%=h e.matricula_antiga %></td>
						<td><%=h e.nome %></td>
						<td><%=h e.cpf %></td>
						<td><%=h e.nome_funcao %></td>
						<td><%=h e.vinculo %></td>
						<td><%=h link_to "Visualizar Detalhadamente.",find_exservidor_omega_path(e.id) %></td>
					</tr>
				<% end %>
			<% end %>
		<% else %>
			<div class="NotFound" id="NenhumaMovimentacao"><%=h image_tag("NotOk.png")+"  Nenhuma movimentação de Fichas de Ex-Servidor do setor casa do Arquivo encontrada no setor de #{@setor.nome}" %></div>
		<% end %>
	</fieldset>
	<div class="flickr_pagination">
      <!-- <div class="page_info"> -->
          <%=h will_paginate @ex_servidores, :previous_label => "Anterior", :next_label => "Próxima", :container => false%>
      <!-- </div> -->
    </div>

<BR />
<div id="side_action_button_fichas_registration">
  	<%=h link_to "Voltar", find_setores_url, :class=>"btn btn-success btn-lg but-shadow btn-size", :id=>"button_font"%>
</div>

app/views/search/locate_matricula.js.erb
$("#fichas").html("<%= escape_javascript(render("find")) %>");

app/views/search/track.html.erb
<DIV class="LadoDoMenu">
  <%=h render 'find' %>
</DIV>

app/views/search/track_by_name.html.erb
<DIV class="LadoDoMenu">
  <%=h render 'find_by_name' %>
</DIV>

app/views/search/track_by_sector.html.erb
<div class="header_scope">
	<%=h link_to "Página Inicial ", sisconff_path, id: "inicial_page" %>
	<%=h link_to ">> Localizar Ficha >> Por Setor", find_setores_path, id: "current_page" %>
</div>
<BR /><BR />
<h4 style="text-align: center;">Setores encontrados na Secretaria Municipal de Administração e Gestão de Pessoas</h4><HR />
<fieldset id="item_destacado">
	
	<% @setores.each do |setor| %>
	<nav>
		<ul id="sectors_founded">
			<li >
				<%=h link_to setor.nome, sectors_located_path(setor.id), id: "sectors_founded"%>
			</li>
		</ul>
	</nav>
  	<% end %>
</fieldset>