config/routes.rb
#encoding:utf-8
ControleFichaFuncional::Application.routes.draw do
  scope '(:locale)' do
    resources :control, :only =>[:index, :get_order_carga],:collection=> { :receive_all => :put } 
    
    resources :usuarios, :only =>[:index, :edit, :update_password]
    
    resources :fichas, :only => [:index, :new, :edit, :create, :update, :destroy]
    
    resources :pensionistas
  
    resources :ex_servidores
    
    resources :line_items
    
    resources :special_line_items
    
    resources :carts
    
    resources :special_carts
    
    resources :order_cargas,:only => [:index, :new, :edit, :create, :destroy]

    resources :special_order_cargas,:only => [:new, :create, :destroy]
    
    resources :search, :only =>[:track, :track_by_sector, :locate_string, :locate_fichas_by_sector]
    
    resources :setores
    # resources :ficha_steps


    devise_for :usuarios
    
    scope "/usuario" do
      get  "/minhas-configurações/edit" => "usuarios#edit", as: :keystroke
      put "/minhas-configurações/update" => "usuarios#update_password", as: :keystroke_update_password
    end

    authenticated :usuario do
      root to: "welcome#sisconff_screen"
    end

    as :order_cargas do
      get "order_cargas/:id" => "order_cargas#show",   as: :order_cargas_id
      get "etiqueta"=> "order_cargas#index", :as=>:view_cargas
      get "/espelho/:id" => "pdf_reports#imprimir_carga", :format => "pdf", :as=> :mirror
    end

    scope '/ex-servidores' do
      as :special_order_cargas do
        get "special_order_cargas/new"=> "special_order_cargas#new",   as: :new_exservidor_cargas
        
        get "special_order_cargas/:id" => "special_order_cargas#show",   as: :exservidor_cargas_id
        # get "exservidor-etiqueta"=> "special_order_cargas#index", :as=>:view_cargas
        get "/exservidor-espelho/:id" => "pdf_reports#imprimir_exservidor_carga", :format => "pdf", :as=> :exservidor_mirror
      
        post "/special_order_cargas/create" => "special_order_cargas#create", as: :special_order_carga_create
        get '/special_order_cargas/ex_servidores/:id', to: 'special_order_cargas#show', as: :special_show_carga
      end
    end

    scope "control" do
      get "/gerenciar/cargas", to: 'control#index', as: :control_set_new_carga
      get "/gerenciar/cargas/ex_servidores", to: 'control#new_ex_serv_frm', as: :control_new_ex_serv_cargas
    end

    scope "visualizar" do
      get '/cargas-pendentes', to: 'control#get_order_carga', as: :control_get_order_carga
      put '/receber-cargas-pendentes', to: 'control#receive_all', as: :control_receive_all
      get '/carga/visualizar-matriculas/:carga_id', to: 'control#view_matriculas', as: :control_view_matriculas
      get '/carga/visualizar-exservidor-matriculas/:special_carga_id', to: 'control#view_exservidor_matriculas', as: :control_view_exservidor_matriculas
    end

    as :search do
      get "search/localizar_ficha_por_matricula/",            to: 'search#track',as: :find_matricula
      get "search/localizar_servidor_por_nome/",            to: 'search#track_by_name',as: :find_server_name
      get "search/ficha/:ficha_id",         to: 'search#locate_ficha',as: :find_ficha_omega
      get "search/exservidor/:exservidor_id",      to: 'search#locate_exservidor',as: :find_exservidor_omega
      get "search/setor/ficha/:ficha_id/exservidor/:exservidor_id",  to: 'search#locate_both',as: :find_paradise_city

      get "search/",  to: 'search#locate_both',as: :find_nome

      get "search/localizar_setores/",            to: 'search#track_by_sector',as: :find_setores  
      get "search/setor/:id",               to: 'search#locate_fichas_by_sector',as: :sectors_located
      
      get "search/localizar_ficha",      to: 'search#localizar', as: :search_string
      get "search/localizar_servidor",      to: 'search#localizar_por_nome', as: :search_server
    end

    as :fichas do
      get "fichas/index"    => "fichas#index",  as: :_fichas
      get "fichas/view/:id" => "fichas#show",   as: :_show_ficha
      get "fichas/new"      => "fichas#new",    as: :_new_ficha
      get "fichas/edit/:id" => "fichas#edit",   as: :_edit_ficha
      get "fichas/create"   => "fichas#create", as: :_create_ficha
      get "fichas/update"   => "fichas#update", as: :_update_ficha
    end

    scope :sisconff do
      get '/sistema-de-controle-de-ficha-funcional', to: "welcome#sisconff_screen", as: :sisconff
      mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
    end

    scope "/welcome" do
      get "/help", to: 'welcome#help', as: :help
    end
    
    root to: "welcome#index", as: 'welcome', via: :all
  end  
end

app/controllers/special_order_cargas_controller.rb
#-*- conding:utf-8 -*-
class SpecialOrderCargasController < ApplicationController
	include CurrentSpecialCart #IMPORTA CURRENT-SPECIAL-CART PARA VERIFICA SE EXISTE UM CARRINHO DE EXSERVIDORES EM SESSÃO
	include SetStatus   #IMPORTA SET-STATUS PARA INICIALIZAR UMA CLASSE STATUS PARA ENTÃO SETAR O ATRIBUTO DE CLASSE STATUS 
	before_action :authenticate_usuario!
	before_action :current_usuario
	before_action :set_special_cart, only: [:new, :create]

	def new
		@special_order_carga = OrderCarga.new

  	case @special_cart
      when @special_cart.special_line_items.empty?
          redirect_to control_new_ex_serv_cargas_path, notice: t('carga.cart_empty')
          return
    end
	end

	def create
		@status = Status.new
    @special_order_carga = OrderCarga.new(order_carga_params)
    @special_order_carga.created_at = Time.now
  
  	@special_order_carga.add_special_line_items_from_special_cart(@special_cart)  
    @special_order_carga.status = @status.set_status_off
  
    respond_to do |format|
      if @special_order_carga.save
        SpecialCart.destroy(session[:special_cart_id])
        session[:special_cart_id] = nil
        
        format.html { redirect_to exservidor_cargas_id_path(@special_order_carga.id), notice: t('carga.successifully_created') }
        format.json { render action: 'index', status: :created, location: @special_order_carga }
      else
        format.html { render action: 'new' }
        format.json { render json: @special_order_carga.errors,
          status: :unprocessable_entity }
      end
    end
	end

	def show
    if current_usuario
      @special_order_carga = OrderCarga.find(params[:id])
      unless @special_order_carga.user_1 == current_usuario
          flash[:error] = t('carga.access_deny')
          redirect_to sisconff_path
      end
    end
  end

	def destroy
    @special_order_carga = OrderCarga.find(params[:id]).destroy
    flash[:notice] = t("carga.successifully_destroyed")
    redirect_to sisconff_path
	end
private
  def order_carga_params
    params.require(:order_carga).permit(:gerada_pelo_usuario_id, :recebida_pelo_usuario_id, :setor_de_origem_id, :setor_de_destino_id, :status)
  end
end

app/helpers/special_order_cargas_helper.rb
module SpecialOrderCargasHelper
end

app/views/special_order_cargas/_form.html.erb
<div class="header_scope">
  <%= link_to "Página Inicial ", sisconff_path, id: "inicial_page" %>
  <%= link_to ">> Gerenciar Cargas Para Ex-Servidores >> Adicionar Matriculas", control_new_ex_serv_cargas_path, id: "middle_page" %>
  <%= link_to " >> Finalizar Carga", new_exservidor_cargas_path, id: "current_page" %>
</div>

<br />
<fieldset><legend><h3>Gerar Carga Para Ex-Servidores</h3></legend>
  <!-- START:explanation -->
  <%= form_for(@special_order_carga, url: special_order_carga_create_path(@special_order_carga) ) do |f| %>
    <% if @special_order_carga.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@order_carga.errors.count, "error") %>
            prohibited this order_carga from being saved:
        </h2>
  <!-- START_HIGHLIGHT -->
        <ul>
        <% @order_carga.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
  <!-- END_HIGHLIGHT -->
        </ul>
      </div>
    <% end %>
  <!-- END:explanation -->

    <div class="field">
      <%= f.hidden_field :gerada_pelo_usuario_id, readonly: true, value: current_usuario.id %>
    </div>

    <div class="field">
      <%= f.hidden_field :setor_de_origem_id, readonly: true, value: current_usuario.setor_id %>
    </div>
    
    <div class="field">
      <%= f.label :setor_de_destino %><br>
      <%= f.collection_select :setor_de_destino_id, Setor.order(:nome), :id, :nome, include_blank: true %>
      <%= error_tag @special_order_carga, :setor_de_destino_id %>
    </div>
    <br />
   
    <div id="side_action_button_fichas_registration">
        <%= f.submit "Gerar", :class=>"button secundary tiny handsover but-rc", :id=>"button_font"%>
    </div>
    <div id="side_action_button_fichas_registration">
      <%= link_to 'Cancelar', control_set_new_carga_path, :class=>"but-primary  but-rc", :id=>"button_font" %>
    </div>
  <% end %>
</fieldset>

app/views/special_order_cargas/destroy.html.slim
h1 SpecialOrderCargas#destroy
p Find me in app/views/special_order_cargas/destroy.html.slim

app/views/special_order_cargas/show.html.erb
<div class="header_scope">
	<%= link_to "Página Inicial >> ", sisconff_path, id: "inicial_page" %>
	<%= link_to "Visualizar Cargas >>", view_cargas_path, id: "middle_page" %>
	<%= link_to "Imprimir Carga", mirror_path(@special_order_carga), id: "current_page", target: 'blank' %>
</div>

<BR />
<BR />

<div class="espelho">
	<div class="espelho_screen">
		<%=h image_tag("brasao_rgb.png", :width => 80, :height => 80) %>
		<div id="espelho_screen_text">
			<%=h "PREFEITURA MUNICIPAL DE CAMPOS DOS GOYTACAZES" %><br />
			<%=h "SECRETARIA MUNICIPAL DE ADMINISTRAÇÃO E GESTÃO DE PESSOAS" %><br />
			<%=h "SISTEMA DE CONTROLE DE FICHAS FUNCIONAIS" %><br />
		</div>
	</div>
	<div id="espelho_screen_bottom">
		<%=h "ESPELHO DE CARGAS ENTRE SETORES - SECRETARIA MUNICIPAL DE ADMINISTRAÇÃO E GESTÃO DE PESSOAS" %><BR /><BR />	

		<div>
			<%=h "Data de criação: " %><%=h @special_order_carga.created_at.strftime("%d/%m/%Y") %>
			<div id="hora_de_criacao">
				<%=h "Hora da criação: "%> <%=h @special_order_carga.created_at.strftime("%H:%M:%S") %>
			</div>
			<div id="usuario_responsavel">
				<%=h "Usuário responsável: "%> <%=h @special_order_carga.user_1.nome %>
			</div>
		</div><BR />

		<div>
			<%=h "Setor de Origem: " %><%=h @special_order_carga.setor_origem.nome %>
		</div>

		<BR />

		<div>
		    <%=h "Setor de Destino: " %><%=h @special_order_carga.setor_destino.nome %>
		</div>

		<BR />

		<DIV class="LadoDoMenu">
		  <table class="pretty">
		 	<tr>
		 		<th> 
		        	<strong><%=h "Nova Matricula Funcional" %></strong>
		      	</th>
		      	<th> 
		        	<strong><%=h "Matricula Funcional Antiga" %></strong>
		      	</th>
		      	<th> 
		        	<strong><%=h "Nome do Servidor" %></strong>
		      	</th>

		      	<th> 
		        	<strong><%=h "CPF" %></strong>
		      	</th>

		      	<th> 
		        	<strong><%=h "Função" %></strong>
		      	</th>

						<th> 
		        	<strong><%=h "Vínculo" %></strong>
		      	</th>
		 	</tr>
			
			<% @special_order_carga.special_line_items.each  do |item| %>
			<tr>    
			    <td>
			    	<center>
			    	  	<%=h formata_matriculas(item.ex_servidor.nova_matricula) %>
			    	</center>
				 </td>

				 <td>
			    	<center>
			    	  	<%=h formata_matriculas(item.ex_servidor.matricula_antiga) %>
			    	</center>
				 </td>

			    <td>
			    	<center>
			    	  	<%=h item.ex_servidor.nome %>
			    	</center>
				  </td>


				    <td>
				    	<center>
				    	  	<%=h item.ex_servidor.cpf %>
				    	</center>
				    </td>

				    <td>
				    	<center><%=h item.ex_servidor.nome_funcao %></center>
				    </td>

			    	<td>
				    	<center><%=h item.ex_servidor.vinculo %></center>
				    </td 
				</tr>
			<% end %>
		</table>
		<%=h "Total de documentos: "%><%=h @special_order_carga.special_line_items.count%>
		</DIV>
	</div>
</div>
<BR />
<BR />
<BR />

<div id="side_action_button_fichas_registration">
	<%=h link_to "Imprimir Carga", exservidor_mirror_path(@special_order_carga), :class=>"button cancel tiny handsover but-rc", :id=>"button_font", :id=>"button_font", target: 'blank'%>
</div>

<div id="side_action_button_fichas_registration">
	<%=h link_to "Voltar", view_cargas_path, :class=>"but-primary  but-rc", :id=>"button_font" %>
</div>