config/routes.rb
#encoding:utf-8
ControleFichaFuncional::Application.routes.draw do
  scope '(:locale)' do
    resources :control, :only =>[:index, :get_order_carga],:collection=> { :receive_all => :put } 
    
    resources :usuarios, :only =>[:index, :edit, :update_password]
    
    resources :fichas, :only => [:index, :new, :edit, :create, :update, :destroy]
    
    resources :pensionistas
  
    resources :ex_servidores
    
    resources :line_items
    
    resources :special_line_items
    
    resources :carts
    
    resources :special_carts
    
    resources :order_cargas,:only => [:index, :new, :edit, :create, :destroy]

    resources :special_order_cargas,:only => [:new, :create, :destroy]
    
    resources :search, :only =>[:track, :track_by_sector, :locate_string, :locate_fichas_by_sector]
    
    resources :setores
    # resources :ficha_steps


    devise_for :usuarios
    
    scope "/usuario" do
      get  "/minhas-configurações/edit" => "usuarios#edit", as: :keystroke
      put "/minhas-configurações/update" => "usuarios#update_password", as: :keystroke_update_password
    end

    authenticated :usuario do
      root to: "welcome#sisconff_screen"
    end

    as :order_cargas do
      get "order_cargas/:id" => "order_cargas#show",   as: :order_cargas_id
      get "etiqueta"=> "order_cargas#index", :as=>:view_cargas
      get "/espelho/:id" => "pdf_reports#imprimir_carga", :format => "pdf", :as=> :mirror
    end

    scope '/ex-servidores' do
      as :special_order_cargas do
        get "special_order_cargas/new"=> "special_order_cargas#new",   as: :new_exservidor_cargas
        
        get "special_order_cargas/:id" => "special_order_cargas#show",   as: :exservidor_cargas_id
        # get "exservidor-etiqueta"=> "special_order_cargas#index", :as=>:view_cargas
        get "/exservidor-espelho/:id" => "pdf_reports#imprimir_exservidor_carga", :format => "pdf", :as=> :exservidor_mirror
      
        post "/special_order_cargas/create" => "special_order_cargas#create", as: :special_order_carga_create
        get '/special_order_cargas/ex_servidores/:id', to: 'special_order_cargas#show', as: :special_show_carga
      end
    end

    scope "control" do
      get "/gerenciar/cargas", to: 'control#index', as: :control_set_new_carga
      get "/gerenciar/cargas/ex_servidores", to: 'control#new_ex_serv_frm', as: :control_new_ex_serv_cargas
    end

    scope "visualizar" do
      get '/cargas-pendentes', to: 'control#get_order_carga', as: :control_get_order_carga
      put '/receber-cargas-pendentes', to: 'control#receive_all', as: :control_receive_all
      get '/carga/visualizar-matriculas/:carga_id', to: 'control#view_matriculas', as: :control_view_matriculas
      get '/carga/visualizar-exservidor-matriculas/:special_carga_id', to: 'control#view_exservidor_matriculas', as: :control_view_exservidor_matriculas
    end

    as :search do
      get "search/localizar_ficha_por_matricula/",            to: 'search#track',as: :find_matricula
      get "search/localizar_servidor_por_nome/",            to: 'search#track_by_name',as: :find_server_name
      get "search/ficha/:ficha_id",         to: 'search#locate_ficha',as: :find_ficha_omega
      get "search/exservidor/:exservidor_id",      to: 'search#locate_exservidor',as: :find_exservidor_omega
      get "search/setor/ficha/:ficha_id/exservidor/:exservidor_id",  to: 'search#locate_both',as: :find_paradise_city

      get "search/",  to: 'search#locate_both',as: :find_nome

      get "search/localizar_setores/",            to: 'search#track_by_sector',as: :find_setores  
      get "search/setor/:id",               to: 'search#locate_fichas_by_sector',as: :sectors_located
      
      get "search/localizar_ficha",      to: 'search#localizar', as: :search_string
      get "search/localizar_servidor",      to: 'search#localizar_por_nome', as: :search_server
    end

    as :fichas do
      get "fichas/index"    => "fichas#index",  as: :_fichas
      get "fichas/view/:id" => "fichas#show",   as: :_show_ficha
      get "fichas/new"      => "fichas#new",    as: :_new_ficha
      get "fichas/edit/:id" => "fichas#edit",   as: :_edit_ficha
      get "fichas/create"   => "fichas#create", as: :_create_ficha
      get "fichas/update"   => "fichas#update", as: :_update_ficha
    end

    scope :sisconff do
      get '/sistema-de-controle-de-ficha-funcional', to: "welcome#sisconff_screen", as: :sisconff
      mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
    end

    scope "/welcome" do
      get "/help", to: 'welcome#help', as: :help
    end
    
    root to: "welcome#index", as: 'welcome', via: :all
  end  
end

app/views/shared/_admin_menu.html.erb
<li>
	<a href="#">
		<span class="iconic key"></span>
		<%= t('usuario.be_welcome', current_user: str_lowercase(current_usuario.nome)) %>
	</a>
	
	<ul>
			<li>
      		<%= link_to rails_admin_path do %>
        		<center>Administrar Site</center>
      		<% end %>
    	</li>
			
	  	<li>
	    	<center><a href="#"><span>Configurações</a></span></center>
	    	<ul>
	      		<li>
	        		<center>
	        			<%= link_to "Alterar dados", edit_usuario_registration_path %>
	        		</center>
	      		</li>
	      		<li>
	        		<center><%= link_to "Alterar senha", keystroke_path %></center>
	      		</li>
	    	</ul> 
	  	</li>
	</ul>
</li>

app/views/shared/_current_user.html.erb
<% unless usuario_signed_in? %>
	
<% else %>
	<div class="wrap_menu">
		<nav class="BORDER_MENU">
		  	<ul class="menu">
		      	<li>
		      		<%= link_to sisconff_path  do %>
						<span class="iconic home"></span>Home
					<% end %>
				</li>
		      	
		      	<!-- <li><a href="#"><span class="iconic magnifying-glass"></span> Relatório</a></li> -->
		      	<% if current_usuario.admin %>
		      		<%= render partial: "shared/admin_menu" %>
		      	<% elsif current_usuario %>
		      		<%= render partial: "shared/usuario_menu" %>
		      	<% end %>
		      	
		      	<li>
		      		<%= link_to destroy_usuario_session_path, :method => :delete do %>
		      			<span class="iconic x-alt"></span><%= t('layout.logout') %>
		      		<% end %>
		      	</li>
			</ul>
		<div class="clearfix"></div>
	</nav><br />
</div>
<BR />
	<div class="current_left_user_menu_help">
		<b><%= link_to t('usuario.need_help'), help_path, id: "current_link" %></b>
	</div>
<% end %>

app/views/shared/_menuLateral.html.erb
<div id="columns">
	<div id="side-menu">
		<% if current_usuario and usuario_signed_in? %>
			<div class="lessSpace">
				<div id="accordian">
					<ul>
						<li>
							<h3><span class="iconic magnifying-glass"></span>Localizar Ficha</h3>
							<ul>
								<li>
									<%= link_to "Por Matricula", find_matricula_path %>
								</li>

								<li>
									<%= link_to "Por Nome", find_server_name_path %>
								</li>
								
								<li>
									<%= link_to "Por Setor", find_setores_path %>
								</li>
							</ul>
						</li>
						<li>
							<h3><span class="iconic rss"></span><%=h "Visualizar Cargas" %></h3>
							<ul>
									<li><%= link_to "Criadas por este Setor", view_cargas_path %></li>
									<li><%= link_to "Pendentes deste Setor",control_get_order_carga_path %></li>
							</ul>
						</li>

						<li>
							<h3><span class="iconic book"></span>Gerenciar Cargas</h3>
							<ul>
								<li><%= link_to "Criar Carga", control_set_new_carga_path %></li>
								<li><%= link_to "Receber Carga",control_get_order_carga_path %></li>	
							</ul>
						</li>
					</ul>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/shared/_messages.html.erb
<div class="sisconff_messages">
	<% flash.each do |key, msg| %>
	  
	  	<div class="flash_messages">
		    <div class="alert alert-<%=h bootstrap_class_messages_for(key)%> alert-<%= key == :notice ? "success" : "error" %>">
		      <a class="close" data-dismiss="alert">&#215;</a>
		      <%=h msg %>
		    </div>
		</div>

	<% end %>
</div>

app/views/shared/_usuario_menu.html.erb
<li>
	<a href="#">
		<span class="iconic user"></span>
		<%= t('usuario.be_welcome', current_user: str_lowercase(current_usuario.nome)) %>
	</a>
	<ul>
	  	<li>
	    	<a href="#"><span>Configurações</a></span>
	    	<ul>
	      		<li>
	        		<center><%= link_to "Alterar dados", edit_usuario_registration_path %></center>
	      		</li>
	      		<li>
	        		<center><%= link_to "Alterar senha", keystroke_path %></center>
	      		</li>
	    	</ul> 
	  	</li><br />
	</ul>
</li>